#define DISTRHO_PLUGIN_NUM_PARAMETERS 4
#define DISTRHO_PLUGIN_START_BUFFERED_PARAMETERS 0
#define DISTRHO_PLUGIN_NUM_BUFFERED_PARAMETERS 3

enum {
	MIDI_MODE_ABSOLUTE,
	MIDI_MODE_RELATIVE,
	MIDI_MODE_COUNT,
};
